#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: R
# autospec version: v21
# autospec commit: f4a13a5
#
Name     : R-pryr
Version  : 0.1.6
Release  : 94
URL      : https://cran.r-project.org/src/contrib/pryr_0.1.6.tar.gz
Source0  : https://cran.r-project.org/src/contrib/pryr_0.1.6.tar.gz
Summary  : Tools for Computing on the Language
Group    : Development/Tools
License  : GPL-2.0
Requires: R-pryr-lib = %{version}-%{release}
Requires: R-Rcpp
Requires: R-lobstr
Requires: R-stringr
BuildRequires : R-Rcpp
BuildRequires : R-lobstr
BuildRequires : R-stringr
BuildRequires : buildreq-R
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
language at a deeper level.

%package lib
Summary: lib components for the R-pryr package.
Group: Libraries

%description lib
lib components for the R-pryr package.


%prep
%setup -q -n pryr
pushd ..
cp -a pryr buildavx2
popd
pushd ..
cp -a pryr buildavx512
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1737154180

%install
export SOURCE_DATE_EPOCH=1737154180
rm -rf %{buildroot}
LANG=C.UTF-8
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -flto -fno-semantic-interposition "
FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -flto -fno-semantic-interposition "
AR=gcc-ar
RANLIB=gcc-ranlib
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library
mkdir -p %{buildroot}-v3/usr/lib64/R/library
mkdir -p %{buildroot}-v4/usr/lib64/R/library
mkdir -p %{buildroot}-va/usr/lib64/R/library

mkdir -p ~/.R
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL  --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}-v3/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --preclean  --install-tests --use-LTO --no-test-load --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}-v4/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean  --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :

/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}
/usr/bin/elf-move.py avx512 %{buildroot}-v4 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/usr/lib64/R/library/pryr/DESCRIPTION
/usr/lib64/R/library/pryr/INDEX
/usr/lib64/R/library/pryr/Meta/Rd.rds
/usr/lib64/R/library/pryr/Meta/features.rds
/usr/lib64/R/library/pryr/Meta/hsearch.rds
/usr/lib64/R/library/pryr/Meta/links.rds
/usr/lib64/R/library/pryr/Meta/nsInfo.rds
/usr/lib64/R/library/pryr/Meta/package.rds
/usr/lib64/R/library/pryr/NAMESPACE
/usr/lib64/R/library/pryr/R/pryr
/usr/lib64/R/library/pryr/R/pryr.rdb
/usr/lib64/R/library/pryr/R/pryr.rdx
/usr/lib64/R/library/pryr/help/AnIndex
/usr/lib64/R/library/pryr/help/aliases.rds
/usr/lib64/R/library/pryr/help/paths.rds
/usr/lib64/R/library/pryr/help/pryr.rdb
/usr/lib64/R/library/pryr/help/pryr.rdx
/usr/lib64/R/library/pryr/html/00Index.html
/usr/lib64/R/library/pryr/html/R.css
/usr/lib64/R/library/pryr/tests/testthat.R
/usr/lib64/R/library/pryr/tests/testthat/helper-object_size.R
/usr/lib64/R/library/pryr/tests/testthat/test-active-binding.r
/usr/lib64/R/library/pryr/tests/testthat/test-bytes.r
/usr/lib64/R/library/pryr/tests/testthat/test-ftype.r
/usr/lib64/R/library/pryr/tests/testthat/test-method-from-call.r
/usr/lib64/R/library/pryr/tests/testthat/test-object_size.R
/usr/lib64/R/library/pryr/tests/testthat/test-track-copy.R

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/R/library/pryr/libs/pryr.so
/V4/usr/lib64/R/library/pryr/libs/pryr.so
/usr/lib64/R/library/pryr/libs/pryr.so
